feat!: added stats and improved configuration format (#51)
* feat: Connection stats

* refactor: Externalized status

* feat: Implemented stat server

* feat: First stat page implementation

* feat: Separated out HTML & JSON

* feat: Report generated

* style: Better display

* feat!: moved to time.Duration for better config

BREAKING CHANGE: everySec -> every - timeoutMilli -> timeout

* ci: 2.0 beta

* doc: Updated README

* feat: added version display

* fix: label tweaks for readability

* fix: missed a couple of cast statements

* fix: formatting

* ci: Trunk upgrade

* style: Displaying durations in seconds

* style: better duration format

* refactor: some renaming

* feat: added info about update count & time

* fix: fixed formatting of 10s

* style: improved report display

* style: stat server info

* refactor: Moved from template to an embedded string

* fix: Fixed go vet error

task: [lint] go vet ./...
Error: internal/statusreport.go:39:12: pattern static/stats.min.html: no matching files found
task: Failed to run task "lint": exit status 1

* fix: head-script-disabled error

* fix: added minification before build

* build: separated out minify from devdep

* feat: added mutex for status access

* fix: atomic status update

* refactor: major refactoring with packages

* refactor: cleaned up naming

* ci: added code coverage testing

* ci: fixed code coverage check

* build: Parallelized tasks through dependencies

* ci: Trunk upgrade

* ci: fixed minification dependencies

* feat: major refactoring of code and build

* refactor: cosmetic renaming of variable

* feat: added downtime to report

* style: HTML tweak

* doc: Added documentation about stats

* ci: Version 2.0 release

* ci: Updated version number

* refactor: Using Prism.js version 1.29.0